version: '3.8'

services:
  db:
    container_name: user-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'crud'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'user123'
      MYSQL_ROOT_PASSWORD: 'user123'
    ports:
      - 3306:3306
    volumes:
      - my-crud:/var/lib/mysql
volumes:
  my-crud: